### ISSUE TITLE
About Model Download

### ISSUE THREAD

**Issue by shenmadouyaowen** [Lipairui/textgo#2]
Hello, where can I download the model **model/word2vec.bin**? I went to h[ttps://huggingface.co/ ](ttps://huggingface.co/ )website to search, did not find

**Comment by Lipairui** [comment]
Hi, some resources of pretrained word2vec models are provided in README ("Pretrained word embeddings"). The model "model/word2vec.bin" is just a demo for illustration.

**Comment by shenmadouyaowen** [comment]
> 嗨，在README中提供了一些预训练的word2vec模型资源（“预训练的词嵌入”）。模型“ model / word2vec.bin”仅是一个演示示例。

ok, thank you
